debug: true

spring:
  aop:
    proxy-target-class: true

security:
  user:
    password: password
  oauth2:
    client:
      clientId: 514021394939-2d5hc030dafqtqvvpk1rfo1f4t3ne59h.apps.googleusercontent.com
      clientSecret: IW4sK2K_nDOc7BcRpepb4DE8
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      scope: "profile email"
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
